name: Deploy Cloudformation Project

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1 
  
            - name: Deploy CloudFormation stack
              run: |
                aws cloudformation deploy \
                --template-file terryResources.yaml \
                --stack-name terryResourceDeploy \
                --capabilities CAPABILITY_NAMED_IAM \
                --parameter-overrides KeyPairName=${{ secrets.KEY_PAIR_NAME }} DBPassword=${{ secrets.DB_PASSWORD }}

        
